#Config file for MdI-Server

#=====================#
#       LOBBYS        #
#=====================#

# Lobbys:
#     ExampleNoPvP:
#         world: worldname
#         xpos: 0
#         ypos: 100
#         zpos: 0
#         gamemode: none
#     ExamplePvP:
#         world: world
#         xpos: 33
#         ypos: 64
#         zPos: 33
#         gamemode: 
#             name: CaptureTheFlag
#             roundlength: 300
#             red: 
#                 spawnx: 0
#                 spawny: 100
#                 spawnz: 0
#             blue: 
#                 spawnx: 20
#                 spawny: 100
#                 spawnz: 20
#
# Gamemodes: CaptureTheFlag, Spleef

# The first specified Lobby should not have a gamemode, because it is the first Lobby the player spawns in.

AntiCheat:
    enabled: true

Lobbys:
    Spawn:
        world: world
        xpos: 0
        ypos: 100
        zpos: 0
        gamemode: none
        
    GTM:
        world: GTM
        xpos: -346
        ypos: 64
        zpos: 160
        gamemode: none
        
    CTF:
        world: world
        xpos: 33
        ypos: 64
        zPos: 33
        gamemode: 
            name: CaptureTheFlag
            roundlength: 300
            teams:
                red: 
                    color: §3
                    spawnx: 0
                    spawny: 100
                    spawnz: 0
                blue: 
                    color: §4
                    spawnx: 20
                    spawny: 100
                    spawnz: 20
        
    Live:
        world: world
        xpos: 33
        ypos: 64
        zPos: 33
        gamemode: 
            name: Lifve
            daytime: 300
            daycoins: 5
            date: 0
            teams:
                red: 
                    color: §3
                    daycoins: 5
                    players:
                        Jannled: true
                        AgeOfBlack: true
                blue: 
                    color: §4
                    daycoins: 5
                    players:
                        Isifninet: true
                        Kattakko: true
