name: MdI-Server
main: com.github.jannled.mdiServer.MdIServer
load: POSTWORLD
version: 0.0.1
author: Jannled
description: One server for many gamemodes

commands: 
    join:
        description: Join a Lobby
        usage: /join [Lobby] <Player>
        permission: mdiServer.join
        permission-message: You are not allowed to forcefully join a lobby!
        
    lobby:
        aliases: [spawn,leave,hub]
        descripton: Return to lobby
        usage: /lobby
        default: true
        permission: mdiServer.join
        permission-message: You are not allowed to join the lobby! Lel I have no clue why...