name: MdI-Server
main: com.github.jannled.mdiServer.MdIServer
load: STARTUP
version: 0.0.1
author: Jannled
description: One server for many gamemodes

commands: 
    join:
        description: Join a Lobby
        usage: /join [Lobby] <Player>
        permission: mdiServer.join
        permission-message: You are not allowed to forcefully join a lobby!
        
    lobby:
        aliases: [spawn,leave,hub]
        descripton: Return to lobby
        usage: /lobby
        default: true
        permission: mdiServer.join
        permission-message: You are not allowed to join the lobby! Lel I have no clue why...
        
    startgame:
        aliases: [start, go, forcestart]
        description: Starts the specified round or the round you are currently in
        usage: /startgame <Lobby>
        permission: mdiServer.startGame
        permission-message: You are not allowed to force the game to start!
        
    goto:
        aliases: [world, changeworld, move]
        description: Move to the specified destination
        usage: /goto [X] [Y] [Z] <World> <PlayerToMove> or /goto <PlayerToMove> [PlayerDestination]
        permission: mdiServer.goto
        permission-message: You are not allowed to teleport!
        
    mdiserver:
        description: Control the MdI-Server Plugin
        usage: /mdiServer reload
        permission: mdiServer.mdiServer
        permission-message: You don't have the control over the server!

    ping:
        description: Get the time the server needs to respond
        usage: /ping
        default: true
        permission: mdiServer.ping
        permission-message: You don't have the permission to let the server ping you!
        
    abilities: 
        description: Manually gives you the desired special abilitie item
        usage: /abilities {SmokeDash/PlayerPickup} <Player>
        default: false
        permission: mdiServer.abilities
        permission-message: You are not allowed to give yourself an abilitie!
